name: kamon
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  animated_text_kit: ^4.2.2
  bloc: ^8.1.3
  cherry_toast: ^1.10.1
  dio: ^5.4.1
  double_back_to_close_app: ^2.1.0
  dynamic_height_grid_view: ^0.0.3
  fancy_shimmer_image: ^2.0.2
  flashy_tab_bar2: ^0.0.10
  get: ^4.6.6
  go_router: ^13.2.1
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.6
  google_sign_in: ^6.2.1
  http: ^1.2.1
  iconsax: ^0.0.8
  image_picker: ^0.8.7+5
  intl: ^0.19.0
  ionicons: ^0.2.2
  lottie: ^3.1.0
  modal_progress_hud_nsn: ^0.5.1
  persistent_bottom_nav_bar: ^5.0.2
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  shimmer: ^2.0.0
  sidebarx: ^0.17.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
